spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr_dev
    username: hr_dev_user
    password: HR
#    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: HR_database_create.sql