create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
create table job_post (id bigint not null auto_increment, description varchar(255), requirement varchar(255), title varchar(255), poster_id bigint, primary key (id)) engine=InnoDB;
create table job_post_skills_needed (job_post_id bigint not null, skills_needed_id bigint not null, primary key (job_post_id, skills_needed_id)) engine=InnoDB;
create table jobpost_user (jobpost_id bigint not null, user_id bigint not null, primary key (jobpost_id, user_id)) engine=InnoDB;
create table job_skill (id bigint not null auto_increment, skill_level integer not null, skill_name varchar(255), job_posted_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email_user varchar(255), first_name varchar(255), image longblob, last_name varchar(255), resume varchar(255), role varchar(255), seniority_level varchar(255), status varchar(255), user_type varchar(255), primary key (id)) engine=InnoDB;
create table user_job_applied (user_id bigint not null, job_applied_id bigint not null, primary key (user_id, job_applied_id)) engine=InnoDB;
create table user_job_posted (user_id bigint not null, job_posted_id bigint not null, primary key (user_id, job_posted_id)) engine=InnoDB;
create table user_user_skills (user_id bigint not null, user_skills_id bigint not null, primary key (user_id, user_skills_id)) engine=InnoDB;
create table user_skill (id bigint not null auto_increment, user_skill_level integer not null, user_skill_name varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
alter table job_post_skills_needed add constraint UK_kka1rikqaoywn09824bkpy43m unique (skills_needed_id);
alter table user_job_posted add constraint UK_8jdo32k3qxse59ii816y5m5h9 unique (job_posted_id);
alter table user_user_skills add constraint UK_2472up7kc2brf5d3ktcylsbui unique (user_skills_id);
alter table job_post add constraint FKf4loq5ts3k2vf2e91p8lbu6m1 foreign key (poster_id) references user (id);
alter table job_post_skills_needed add constraint FKpnndd1u88yyn0f3t11161y9pb foreign key (skills_needed_id) references job_skill (id);
alter table job_post_skills_needed add constraint FK3kllpukkb2m2jhle6jwwilap foreign key (job_post_id) references job_post (id);
alter table jobpost_user add constraint FK6j41tf5fs6ns5k328s06f185f foreign key (user_id) references user (id);
alter table jobpost_user add constraint FKr7fcof4yfh2me120vlc1xko0h foreign key (jobpost_id) references job_post (id);
alter table job_skill add constraint FKospyskmob16knlg8tceitb369 foreign key (job_posted_id) references job_post (id);
alter table user_job_applied add constraint FKiq399s7k6htqf1dxg7nt8stk1 foreign key (job_applied_id) references job_post (id);
alter table user_job_applied add constraint FK7ejpvsl034stgva85pqqxo5ow foreign key (user_id) references user (id);
alter table user_job_posted add constraint FKc71dee5sl9dnvawropqa40ve8 foreign key (job_posted_id) references job_post (id);
alter table user_job_posted add constraint FKt9lhr11eygl1a57ya7m1nuu3c foreign key (user_id) references user (id);
alter table user_user_skills add constraint FKmgaevocklquhpfa0y99apnjcd foreign key (user_skills_id) references user_skill (id);
alter table user_user_skills add constraint FK4ff83ex4tm7wuhatruy1xtpsg foreign key (user_id) references user (id);
alter table user_skill add constraint FKfixgsonf2ev168mfck7co17u1 foreign key (user_id) references user (id);
